"""
Database connection management for Oracle database.
"""
import oracledb
from contextlib import contextmanager
from typing import Optional, Generator
import logging
from .config import config

logger = logging.getLogger(__name__)


class DatabaseConnection:
    """Manages Oracle database connections and operations."""

    def __init__(self):
        self.pool: Optional[oracledb.ConnectionPool] = None
        self._init_pool()

    def _init_pool(self):
        """Initialize connection pool."""
        try:
            # Configure Oracle client if needed (skip if credentials not provided)
            if not all([config.oracle_user, config.oracle_password, config.oracle_dsn]):
                print("Oracle credentials not configured - database operations will fail")
                self.pool = None
                return

            # Try to initialize Oracle client (may not be needed in all environments)
            #try:
            #    oracledb.init_oracle_client()
            #except Exception as e:
            #    print(f"Oracle client initialization warning: {e}")

            self.pool = oracledb.create_pool(
                user=config.oracle_user,
                password=config.oracle_password,
                dsn=config.oracle_dsn,
                config_dir=config.oracle_wallet,
                wallet_location=config.oracle_wallet,
                wallet_password=config.oracle_wallet_pass,
                min=2,
                max=10,
                increment=1,
                getmode=oracledb.POOL_GETMODE_WAIT,
                timeout=30,
            )
            print("Oracle connection pool initialized successfully")
        except Exception as e:
            print(f"Failed to initialize Oracle connection pool: {e}")
            self.pool = None

    @contextmanager
    def get_connection(self) -> Generator[oracledb.Connection, None, None]:
        """Get a database connection from the pool."""
        if self.pool is None:
            raise Exception("Database connection pool not initialized")

        connection = None
        try:
            connection = self.pool.acquire()
            yield connection
        finally:
            if connection:
                self.pool.release(connection)

    def execute_query(self, query: str, params: Optional[tuple | dict] = None, fetch: bool = True):
        """Execute a SELECT query and return results."""
        with self.get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(query, params or ())
                if fetch:
                    return cursor.fetchall()
                return None

    def execute_dml(self, query: str, params: Optional[tuple | dict] = None) -> int:
        """Execute INSERT, UPDATE, DELETE queries."""
        with self.get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(query, params or ())
                conn.commit()
                return cursor.rowcount

    def test_connection(self) -> bool:
        """Test database connection."""
        try:
            result = self.execute_query("SELECT 1 FROM DUAL")
            return result is not None and len(result) > 0
        except Exception as e:
            print(f"Database connection test failed: {e}")
            return False

    def initialize_schema(self):
        """Initialize database schema if tables don't exist."""
        try:
            # Check if MAC_PC column exists, add it if not
            try:
                result = self.execute_query("SELECT MAC_PC FROM STUDENTS WHERE ROWNUM = 1")
            except Exception:
                logger.info("Adding MAC_PC column to STUDENTS table...")
                self.execute_dml("ALTER TABLE STUDENTS ADD (MAC_PC CHAR(1) CHECK (MAC_PC IN ('M', 'P')))")

            # Check if ONBOARDING_TASKS table exists, create it if not
            try:
                result = self.execute_query("SELECT COUNT(*) FROM ONBOARDING_TASKS WHERE ROWNUM = 1")
            except Exception:
                logger.info("Creating ONBOARDING_TASKS table...")
                create_tasks_table = """
                CREATE TABLE ONBOARDING_TASKS (
                    TASK_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    STUDENT_ID VARCHAR2(50) REFERENCES STUDENTS(STUDENT_ID),
                    TASK_CODE VARCHAR2(50) NOT NULL,
                    COMPLETED CHAR(1) DEFAULT 'N' CHECK (COMPLETED IN ('Y', 'N')),
                    COMPLETED_AT TIMESTAMP,
                    UNIQUE(STUDENT_ID, TASK_CODE)
                )
                """
                self.execute_dml(create_tasks_table)

            # Check if SURVEY_RESPONSES table exists, create it if not
            try:
                result = self.execute_query("SELECT COUNT(*) FROM SURVEY_RESPONSES WHERE ROWNUM = 1")
            except Exception:
                logger.info("Creating SURVEY_RESPONSES table...")
                create_survey_table = """
                CREATE TABLE SURVEY_RESPONSES (
                    RESPONSE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    STUDENT_ID VARCHAR2(50) REFERENCES STUDENTS(STUDENT_ID),
                    SURVEY_TYPE VARCHAR2(50) NOT NULL,
                    RATING NUMBER(1) CHECK (RATING BETWEEN 1 AND 5),
                    WHAT_LIKED VARCHAR2(2000),
                    WHAT_BETTER VARCHAR2(2000),
                    COMMENTS CLOB,
                    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """
                self.execute_dml(create_survey_table)

            # Check if WORKSHOP_FEEDBACK table exists, create it if not
            try:
                result = self.execute_query("SELECT COUNT(*) FROM WORKSHOP_FEEDBACK WHERE ROWNUM = 1")
            except Exception:
                logger.info("Creating WORKSHOP_FEEDBACK table...")
                create_feedback_table = """
                CREATE TABLE WORKSHOP_FEEDBACK (
                    FEEDBACK_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    STUDENT_ID VARCHAR2(50) REFERENCES STUDENTS(STUDENT_ID),
                    OVERALL_RATING NUMBER(1) CHECK (OVERALL_RATING BETWEEN 1 AND 5),
                    OVERALL_COMMENTS CLOB,
                    FUTURE_IDEAS CLOB,
                    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """
                self.execute_dml(create_feedback_table)

            # Check if LOCATIONS table exists, create it if not
            try:
                result = self.execute_query("SELECT COUNT(*) FROM LOCATIONS WHERE ROWNUM = 1")
            except Exception:
                logger.info("Creating LOCATIONS table...")
                create_locations_table = """
                CREATE TABLE LOCATIONS (
                    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    CODE VARCHAR2(3) UNIQUE NOT NULL,
                    NAME VARCHAR2(50) NOT NULL,
                    ROOM VARCHAR2(50) NOT NULL,
                    MEETING_TIME VARCHAR2(20) NOT NULL,
                    AGENDA_IMAGE_PATH VARCHAR2(100) NOT NULL
                )
                """
                self.execute_dml(create_locations_table)

                # Insert location data if table is newly created
                locations_data = [
                    ("DEL", "Delhi", "DEL-101", "9:00 AM - 5:00 PM", "images/agenda-del.png"),
                    ("BLR", "Bangalore", "BLR-202", "10:00 AM - 6:00 PM", "images/agenda-blr.png"),
                    ("HYD", "Hyderabad", "HYD-303", "11:00 AM - 7:00 PM", "images/agenda-hyd.png")
                ]
                insert_location = """
                INSERT INTO LOCATIONS (CODE, NAME, ROOM, MEETING_TIME, AGENDA_IMAGE_PATH)
                VALUES (:code, :name, :room, :time, :image_path)
                """
                for data in locations_data:
                    try:
                        self.execute_dml(insert_location, data)
                    except Exception as e:
                        logger.warning(f"Failed to insert location {data[0]}: {e}")

            logger.info("Database schema initialization completed successfully")
            return True

        except Exception as e:
            logger.error(f"Error initializing database schema: {e}")
            return False


# Global database instance
db = DatabaseConnection()
